version: '3.1'
services:

  nginx:
    image: todolist_project/nginx:latest
    build:
      context: nginx
    environment:
      WEBSERVER_PORT: ${WEBSERVER_PORT}
    ports:
      - ${WEBSERVER_PORT}:${WEBSERVER_PORT}

  db:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
    - ${PHPMYADMIN_PORT}:80
    environment:
    - PMA_ARBITRARY=1
    - MYSQL_USER=root
    - PMA_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
    - db

  todolist:
    image: todolist_project/todolist:latest
    build:
      context: .
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
    volumes:
      - ./todolist:/var/www/html/public

volumes:
  db_data: